try:
    int("a0")
except Exception as e:
    print("Ocurri√≥ un error.",e.__class__)
else:
    print("todo salio bien")
finally:
    print("Final del bloque")